name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Build
        run: go build -v .

      - name: Import test GPG key
        run: gpg --import test/testing-key.pgp

      - name: Test
        run: make test

      - name: Crossbuild
        run: make crossbuild
